# air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -buildvcs=false -o ./tmp/main ."
  bin = "tmp/main"
  include = ["*.go"]  # Include all .go files in the root directory
  exclude = ["tmp/**"] # Exclude anything in the tmp directory

[watch]
  include = ["*.go"]  # Watch all .go files in the root directory
  exclude = ["tmp/**"] # Exclude tmp directory from being watched

[log]
  level = "debug"  # Set logging level to debug for more details
