# middleware_groups:
#   auth_group:
#     - auth_middleware
#   ratelimit_group:
#     - auth_middleware
#     - ratelimit_middleware
#   all_group:
#     - auth_middleware
#     - nocache_middleware

# routes:
#   - prefix: "/dummy"
#     middleware:
#       - auth_middleware
#     paths:
#       - method: "GET"
#         path: "/docs/todos"
#         proxy_target: "https://dummyjson.com"

#   - prefix: "/dummy2"
#     middleware_group: "ratelimit_group"
#     method: "GET"
#     proxy_target: "https://dummyjson.com"

# REMOVE METHOD FROM HGERE

# - prefix: "/redirect-dummy"
#   method: "GET"
#   redirect_target: "https://dummyjson.com/docs/todos"

# - prefix: "/redirect-dummy-path"
#   paths:
#     - path: "/docs"
#       redirect_target: "https://dummyjson.com/docs"
#     - path: "/docs/todos"
#       redirect_target: "https://dummyjson.com/docs/todos"

rate_limiters:
  fw_1:
    ttl: "8h"
    cleanup_interval: "2h"
    algorithm: "fixed_window_counter"
    limit: 10
    window_size: "5s"
  tb_1:
    ttl: "8h"
    cleanup_interval: "2h"
    algorithm: "token_bucket"
    capacity: 10
    refill_tokens: 10
    refill_interval: "5s"

forward_auth:
  jwt:
    url: "https://auth.cizzle.cloud/access-token/verify"
    timeout: "5s"
    request_headers: ["Authorization"]
    trust_forward_header: true
    forward_body: true

  session:
    url: "https://auth.cizzle.cloud/validate"
    timeout: "5s"

domain_routes:
  - domain: "www.localhost.com"
    proxy_target: "https://dummyjson.com"

  - domain: "www.localhost.com"
    proxy_target: "https://dummyjson.com"

  - domain: "www.spacenarratives.gr"
    middleware:
      - "fw_1"
    proxy_target: "https://dummyjson.com"

env:
  PORT: "80"
  HOST: "0.0.0.0"
  VALIDATE_AUTH_URL: "test1"
  REDIRECT_UNAUTHORIZED_URL: "test2"
