# middleware_groups:
#   auth_group:
#     - auth_middleware
#   ratelimit_group:
#     - auth_middleware
#     - ratelimit_middleware
#   all_group:
#     - auth_middleware
#     - nocache_middleware

# routes:
#   - prefix: "/dummy"
#     middleware:
#       - auth_middleware
#     paths:
#       - method: "GET"
#         path: "/docs/todos"
#         proxy_target: "https://dummyjson.com"

#   - prefix: "/dummy2"
#     middleware_group: "ratelimit_group"
#     method: "GET"
#     proxy_target: "https://dummyjson.com"

#   - prefix: "/redirect-dummy"
#     method: "GET"
#     redirect_target: "https://dummyjson.com/docs/todos"

#   - prefix: "/redirect-dummy-path"
#     paths:
#       - method: "GET"
#         path: "/docs"
#         redirect_target: "https://dummyjson.com/docs"
#       - method: "GET"
#         path: "/docs/todos"
#         redirect_target: "https://dummyjson.com/docs/todos"

rate_limiters:
  fw_1:
    algorithm: "fixed_window_counter"
    limit: 10
    window_size: 500
  tb_1:
    algorithm: "token_bucket"
    capacity: 10
    refill_tokens: 5
    refill_interval: 500



domain_routes:
  - domain: "www.localhost.com"
    proxy_target: "https://dummyjson.com"

  - domain: "www.localhost.com"
    proxy_target: "https://dummyjson.com"

  - domain: "www.spacenarratives.gr"
    middleware:
      - "fw_1"
    proxy_target:  "https://dummyjson.com"


    
env:
  PORT: "80"
  HOST: "0.0.0.0"
  VALIDATE_AUTH_URL: "test1"
  REDIRECT_UNAUTHORIZED_URL: "test2"
