name: Build and Push docker image to GHCR

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Set up Git to use GitHub Token
        run: |
          git config --global url."https://${{ secrets.GHCR_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -v

  build-and-push:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key
          docker build --secret id=ssh,src=ssh_key \
            -f Dockerfile.prod \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/api-gateway:latest \
            .
        env:
          DOCKER_BUILDKIT: 1

      - name: Push
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/api-gateway:latest
