name: Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"

      - name: Set up Git to use GitHub Token
        run: |
          git config --global url."https://${{ secrets.GHCR_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Install dependencies
        run: go mod download && go mod verify

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./...
